# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{howkast}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Juris Galang"]
  s.date = %q{2010-12-30}
  s.description = %q{
    This gem implements Ruby bindings for the [Howcast](http://howcast.com) API
    Howcast empowers people with engaging, useful how-to information wherever, whenever they need to know how.
  }
  s.email = %q{jurisgalang@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "GPL-LICENSE",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.md",
    "RELEASENOTES",
    "Rakefile",
    "VERSION",
    "features/howkast.feature",
    "features/step_definitions/howkast_steps.rb",
    "features/support/env.rb",
    "howkast.gemspec",
    "lib/howkast.rb",
    "lib/howkast/api.rb",
    "lib/howkast/base.rb",
    "lib/howkast/configuration.rb",
    "lib/howkast/errors.rb",
    "lib/howkast/ext/icebox.rb",
    "lib/howkast/ext/string.rb",
    "lib/howkast/model.rb",
    "lib/howkast/processors/base.rb",
    "lib/howkast/processors/categories.rb",
    "lib/howkast/processors/playlists.rb",
    "lib/howkast/processors/search.rb",
    "lib/howkast/processors/users.rb",
    "lib/howkast/processors/videos.rb",
    "sample/quickstart.rb",
    "spec/howkast/api_service_spec.rb",
    "spec/howkast/api_spec.rb",
    "spec/howkast/model_spec.rb",
    "spec/howkast/processors/categories_spec.rb",
    "spec/howkast/processors/playlists_spec.rb",
    "spec/howkast/processors/search_spec.rb",
    "spec/howkast/processors/users_spec.rb",
    "spec/howkast/processors/videos_spec.rb",
    "spec/howkast_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jurisgalang/howkast}
  s.licenses = [["MIT", "GPL"]]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby bindings for the [Howcast](http://howcast.com) API}
  s.test_files = [
    "spec/howkast/api_service_spec.rb",
    "spec/howkast/api_spec.rb",
    "spec/howkast/model_spec.rb",
    "spec/howkast/processors/categories_spec.rb",
    "spec/howkast/processors/playlists_spec.rb",
    "spec/howkast/processors/search_spec.rb",
    "spec/howkast/processors/users_spec.rb",
    "spec/howkast/processors/videos_spec.rb",
    "spec/howkast_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

